
/**
* FileInterfaceOperations.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from FileInterface.idl
* jueves 6 de mayo de 2021 03:56:55 PM GMT
*/

public interface FileInterfaceOperations 
{
  String ContarLineas (String archivo);
  String ContarVocales (String archivo);
  void Escribe (String archivo, String contenido);
  String Imprimir (String archivo);
  void Respaldar (String archivo, String respaldo);
  void Copiar (String archivo, String archivin);
  void Renombrar (String archivo, String renombrado);
  boolean Borrar (String archivo);
} // interface FileInterfaceOperations
